env:
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "prettier"
plugins:
  - "unused-imports"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "quotes": ["error", "single"],
  "no-tabs": 0,
  "no-unused-vars": "off",
  "unused-imports/no-unused-imports": "error",
  "unused-imports/no-unused-vars": [
    "warn",
    {
      "vars": "all",
      "varsIgnorePattern": "^_",
      "args": "after-used",
      "argsIgnorePattern": "^_"
    }
  ]
}
