# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Realease

on:
  workflow_dispatch:
    
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    environment: NPM
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.name 'Fabian Will'
      - run: git config --global user.email 'mail@fwill.dev'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
